apiVersion: v1
kind: ReplicationController
metadata:
  name: onkyo-rc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: onkyo
    spec:
      containers:
      - name: onkyo
        image: seanmcguigan/app:1.0.1
        ports:
        - containerPort: 80
